name: crowd-label-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-n-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install-dev
    - name: Lint
      run: |
        make lint
    - name: Type check
      run: |
        make typing-py
    - name: Test with pytest
      run: |
        make test
